/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WebsitesWebsiteIdRouteImport } from './routes/websites.$websiteId'
import { Route as EmbedMapRouteImport } from './routes/embed/map'
import { Route as EmbedLiveRouteImport } from './routes/embed/live'
import { Route as EmbedChartRouteImport } from './routes/embed/chart'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsitesWebsiteIdRoute = WebsitesWebsiteIdRouteImport.update({
  id: '/websites/$websiteId',
  path: '/websites/$websiteId',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedMapRoute = EmbedMapRouteImport.update({
  id: '/embed/map',
  path: '/embed/map',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedLiveRoute = EmbedLiveRouteImport.update({
  id: '/embed/live',
  path: '/embed/live',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedChartRoute = EmbedChartRouteImport.update({
  id: '/embed/chart',
  path: '/embed/chart',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/embed/chart': typeof EmbedChartRoute
  '/embed/live': typeof EmbedLiveRoute
  '/embed/map': typeof EmbedMapRoute
  '/websites/$websiteId': typeof WebsitesWebsiteIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/embed/chart': typeof EmbedChartRoute
  '/embed/live': typeof EmbedLiveRoute
  '/embed/map': typeof EmbedMapRoute
  '/websites/$websiteId': typeof WebsitesWebsiteIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/embed/chart': typeof EmbedChartRoute
  '/embed/live': typeof EmbedLiveRoute
  '/embed/map': typeof EmbedMapRoute
  '/websites/$websiteId': typeof WebsitesWebsiteIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/embed/chart'
    | '/embed/live'
    | '/embed/map'
    | '/websites/$websiteId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/embed/chart'
    | '/embed/live'
    | '/embed/map'
    | '/websites/$websiteId'
  id:
    | '__root__'
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/embed/chart'
    | '/embed/live'
    | '/embed/map'
    | '/websites/$websiteId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  EmbedChartRoute: typeof EmbedChartRoute
  EmbedLiveRoute: typeof EmbedLiveRoute
  EmbedMapRoute: typeof EmbedMapRoute
  WebsitesWebsiteIdRoute: typeof WebsitesWebsiteIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/websites/$websiteId': {
      id: '/websites/$websiteId'
      path: '/websites/$websiteId'
      fullPath: '/websites/$websiteId'
      preLoaderRoute: typeof WebsitesWebsiteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/map': {
      id: '/embed/map'
      path: '/embed/map'
      fullPath: '/embed/map'
      preLoaderRoute: typeof EmbedMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/live': {
      id: '/embed/live'
      path: '/embed/live'
      fullPath: '/embed/live'
      preLoaderRoute: typeof EmbedLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/chart': {
      id: '/embed/chart'
      path: '/embed/chart'
      fullPath: '/embed/chart'
      preLoaderRoute: typeof EmbedChartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  EmbedChartRoute: EmbedChartRoute,
  EmbedLiveRoute: EmbedLiveRoute,
  EmbedMapRoute: EmbedMapRoute,
  WebsitesWebsiteIdRoute: WebsitesWebsiteIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
